#!/usr/bin/expect -f
spawn nvim demo
send -- ":T watch -n 0.1 -t tree demo/\r"
interact timeout 2 return
send -- "cefolder\033"
interact timeout 2 return
send -- "\r"
interact timeout 2 return
send -- "\r"
interact timeout 2 return
send -- "-"
interact timeout 2 return
send -- "yy"
interact timeout 2 return
send -- "p"
interact timeout 2 return
send -- "\b\b\b\b_copy\r"
interact timeout 2 return
exit
